version: "3.8"

services:
  travle-API:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: travle-API
    environment:
      ACCEPT_EULA: Y
      SA_PASSWORD: lilium_bosniacum
    ports:
      - "1435:1433"
    expose:
      - "1433"
    volumes:
      - sqlserver_data:/var/opt/mssql

volumes:
  sqlserver_data:
