namespace Travle.Services.Database.Seeding
{
    /// <summary>A country and the regions it contains, for the reference-data expansion.</summary>
    internal sealed record CountrySeed(string Name, RegionSeed[] Regions);

    /// <summary>A region and the cities it groups.</summary>
    internal sealed record RegionSeed(string Name, string[] Cities);

    /// <summary>
    /// Static geographic reference set expanded by <see cref="BulkSeeder"/> (the sanctioned "rich data →
    /// runtime seeder" path, 02 §4). Bosnia and Herzegovina uses a nature/geography-based, non-political
    /// regional division (approved taxonomy); Croatia uses macro-regions; the rest of the Balkans get their
    /// major cities and every other UN member gets its capital (plus a couple of notable cities). The upsert
    /// is name-based and country-scoped, so it is the single source of truth for the reference geography and
    /// re-running is a no-op.
    /// </summary>
    internal static class SeedGeography
    {
        private static CountrySeed One(string country, params string[] cities) =>
            new(country, [new RegionSeed(country, cities)]);

        public static readonly CountrySeed[] Countries =
        {
            // ---- Bosnia and Herzegovina: 11 nature/geography-based regions (approved taxonomy) ----
            new("Bosnia and Herzegovina",
            [
                new RegionSeed("Sarajevo Region",
                    ["Sarajevo", "Ilidža", "Vogošća", "Hadžići", "Ilijaš", "Trnovo", "Pale"]),
                new RegionSeed("Central Bosnia (Lašva-Vrbas)",
                    ["Travnik", "Vitez", "Novi Travnik", "Busovača", "Fojnica", "Kiseljak", "Kreševo",
                     "Bugojno", "Gornji Vakuf", "Donji Vakuf", "Jajce"]),
                new RegionSeed("Zenica & the Bosna Valley",
                    ["Zenica", "Kakanj", "Visoko", "Breza", "Vareš", "Olovo", "Žepče", "Zavidovići",
                     "Maglaj", "Tešanj", "Usora", "Doboj Jug"]),
                new RegionSeed("Bosanska Krajina (Una-Sana)",
                    ["Bihać", "Cazin", "Velika Kladuša", "Bosanska Krupa", "Bužim", "Sanski Most", "Ključ",
                     "Bosanski Petrovac", "Drvar", "Prijedor", "Bosanski Novi", "Bosanska Dubica", "Bosanska Kostajnica", "Ribnik"]),
                new RegionSeed("Livno Region",
                    ["Livno", "Duvno", "Kupres", "Glamoč", "Bosansko Grahovo"]),
                new RegionSeed("West Herzegovina",
                    ["Široki Brijeg", "Ljubuški", "Grude", "Posušje"]),
                new RegionSeed("Central Herzegovina",
                    ["Mostar", "Blagaj", "Počitelj", "Čitluk", "Čapljina", "Stolac", "Konjic", "Jablanica", "Neum", "Prozor"]),
                new RegionSeed("East Herzegovina",
                    ["Trebinje", "Bileća", "Gacko", "Nevesinje", "Ljubinje", "Berkovići"]),
                new RegionSeed("North Bosnia (Posavina & Banja Luka-Doboj)",
                    ["Banja Luka", "Laktaši", "Bosanska Gradiška", "Prnjavor", "Srbac", "Čelinac", "Kotor Varoš",
                     "Teslić", "Mrkonjić Grad", "Šipovo", "Jezero", "Skender Vakuf", "Doboj", "Derventa",
                     "Modriča", "Bosanski Šamac", "Odžak", "Orašje", "Bosanski Brod", "Bosansko Petrovo Selo", "Vukosavlje", "Donji Žabar"]),
                new RegionSeed("Northeast Bosnia (Tuzla & Semberija)",
                    ["Tuzla", "Lukavac", "Živinice", "Banovići", "Gračanica", "Gradačac", "Srebrenik",
                     "Kalesija", "Sapna", "Teočak", "Čelić", "Lopare", "Ugljevik", "Bijeljina", "Zvornik",
                     "Kladanj", "Doboj Istok"]),
                new RegionSeed("East Bosnia (Podrinje)",
                    ["Foča", "Goražde", "Višegrad", "Rudo", "Čajniče", "Rogatica", "Sokolac", "Han Pijesak",
                     "Vlasenica", "Milići", "Šekovići", "Srebrenica", "Bratunac", "Ustiprača", "Ustikolina"]),
            ]),

            // ---- Croatia: macro-regions ----
            new("Croatia",
            [
                new RegionSeed("Dalmatia",
                    ["Split", "Zadar", "Šibenik", "Dubrovnik", "Trogir", "Kaštela", "Sinj", "Makarska",
                     "Omiš", "Knin", "Solin", "Metković", "Ploče", "Nin", "Hvar", "Korčula", "Vis", "Ston",
                     "Cavtat", "Biograd na Moru"]),
                new RegionSeed("Istria",
                    ["Pula", "Poreč", "Rovinj", "Umag", "Pazin", "Labin", "Buzet", "Motovun"]),
                new RegionSeed("Kvarner",
                    ["Rijeka", "Opatija", "Crikvenica", "Krk", "Mali Lošinj", "Rab", "Delnice"]),
                new RegionSeed("Lika",
                    ["Gospić", "Otočac", "Senj", "Korenica"]),
                new RegionSeed("Central Croatia",
                    ["Zagreb", "Velika Gorica", "Samobor", "Zaprešić", "Karlovac", "Sisak", "Jastrebarsko"]),
                new RegionSeed("Zagorje & Međimurje",
                    ["Varaždin", "Čakovec", "Krapina", "Zabok"]),
                new RegionSeed("Slavonia",
                    ["Osijek", "Slavonski Brod", "Vinkovci", "Vukovar", "Đakovo", "Požega", "Bjelovar",
                     "Koprivnica", "Virovitica", "Nova Gradiška"]),
            ]),

            // ---- Rest of the Balkans / SE Europe (major cities) ----
            One("Serbia", "Belgrade", "Novi Sad", "Niš", "Kragujevac", "Subotica", "Zrenjanin", "Pančevo",
                "Čačak", "Kraljevo", "Novi Pazar"),
            One("Montenegro", "Podgorica", "Nikšić", "Herceg Novi", "Kotor", "Budva", "Bar", "Cetinje",
                "Bijelo Polje", "Tivat", "Ulcinj"),
            One("Kosovo", "Pristina", "Prizren", "Peja", "Gjakova", "Mitrovica", "Ferizaj", "Gjilan",
                "Vushtrri", "Podujeva"),
            One("North Macedonia", "Skopje", "Bitola", "Ohrid", "Tetovo", "Kumanovo", "Prilep", "Struga",
                "Štip", "Strumica"),
            One("Albania", "Tirana", "Durrës", "Vlorë", "Shkodër", "Elbasan", "Berat", "Gjirokastër",
                "Sarandë", "Korçë"),
            One("Slovenia", "Ljubljana", "Maribor", "Celje", "Kranj", "Koper", "Bled", "Ptuj",
                "Novo Mesto", "Piran"),
            One("Bulgaria", "Sofia", "Plovdiv", "Varna", "Burgas", "Ruse", "Veliko Tarnovo", "Nesebar", "Bansko"),
            One("Greece", "Athens", "Thessaloniki", "Patras", "Heraklion", "Rhodes", "Corfu", "Nafplio",
                "Kalambaka"),
            One("Romania", "Bucharest", "Cluj-Napoca", "Brașov", "Timișoara", "Sibiu", "Constanța"),
            One("Turkey", "Ankara", "Istanbul", "Izmir", "Antalya", "Bursa", "Trabzon"),

            // ---- Rest of Europe ----
            One("Austria", "Vienna", "Graz", "Salzburg", "Innsbruck"),
            One("Germany", "Berlin", "Munich", "Hamburg", "Frankfurt", "Cologne"),
            One("Switzerland", "Bern", "Zurich", "Geneva", "Lucerne"),
            One("Italy", "Rome", "Milan", "Venice", "Florence", "Naples"),
            One("France", "Paris", "Lyon", "Marseille", "Nice"),
            One("Spain", "Madrid", "Barcelona", "Seville", "Valencia"),
            One("Portugal", "Lisbon", "Porto", "Faro"),
            One("Netherlands", "Amsterdam", "Rotterdam", "The Hague", "Utrecht"),
            One("Belgium", "Brussels", "Antwerp", "Bruges", "Ghent"),
            One("Luxembourg", "Luxembourg City"),
            One("United Kingdom", "London", "Manchester", "Edinburgh", "Birmingham"),
            One("Ireland", "Dublin", "Cork", "Galway"),
            One("Denmark", "Copenhagen", "Aarhus", "Odense"),
            One("Norway", "Oslo", "Bergen", "Trondheim"),
            One("Sweden", "Stockholm", "Gothenburg", "Malmö"),
            One("Finland", "Helsinki", "Tampere", "Turku"),
            One("Iceland", "Reykjavik", "Akureyri"),
            One("Poland", "Warsaw", "Kraków", "Gdańsk", "Wrocław"),
            One("Czechia", "Prague", "Brno", "Ostrava", "Český Krumlov"),
            One("Slovakia", "Bratislava", "Košice", "Žilina"),
            One("Hungary", "Budapest", "Debrecen", "Szeged", "Pécs"),
            One("Ukraine", "Kyiv", "Lviv", "Odesa", "Kharkiv"),
            One("Belarus", "Minsk", "Brest", "Grodno"),
            One("Moldova", "Chișinău", "Bălți", "Tiraspol"),
            One("Russia", "Moscow", "Saint Petersburg", "Kazan", "Sochi"),
            One("Estonia", "Tallinn", "Tartu"),
            One("Latvia", "Riga", "Daugavpils"),
            One("Lithuania", "Vilnius", "Kaunas", "Klaipėda"),
            One("Malta", "Valletta", "Mdina"),
            One("Cyprus", "Nicosia", "Limassol", "Paphos"),
            One("Andorra", "Andorra la Vella"),
            One("Monaco", "Monaco"),
            One("San Marino", "San Marino"),
            One("Liechtenstein", "Vaduz"),

            // ---- Middle East ----
            One("Palestine", "Jerusalem", "Gaza", "Bethlehem", "Hebron", "Haifa"),
            One("Jordan", "Amman", "Petra", "Aqaba"),
            One("Lebanon", "Beirut", "Byblos", "Tripoli"),
            One("Syria", "Damascus", "Aleppo", "Palmyra"),
            One("Iraq", "Baghdad", "Basra", "Erbil"),
            One("Iran", "Tehran", "Isfahan", "Shiraz"),
            One("Saudi Arabia", "Riyadh", "Jeddah", "Mecca", "Medina"),
            One("United Arab Emirates", "Abu Dhabi", "Dubai", "Sharjah"),
            One("Qatar", "Doha"),
            One("Bahrain", "Manama"),
            One("Kuwait", "Kuwait City"),
            One("Oman", "Muscat", "Nizwa"),
            One("Yemen", "Sana'a", "Aden"),

            // ---- Central & South Asia ----
            One("Kazakhstan", "Astana", "Almaty"),
            One("Uzbekistan", "Tashkent", "Samarkand", "Bukhara"),
            One("Turkmenistan", "Ashgabat"),
            One("Kyrgyzstan", "Bishkek", "Osh"),
            One("Tajikistan", "Dushanbe"),
            One("Afghanistan", "Kabul", "Herat"),
            One("Pakistan", "Islamabad", "Karachi", "Lahore"),
            One("India", "New Delhi", "Mumbai", "Bengaluru", "Jaipur"),
            One("Nepal", "Kathmandu", "Pokhara"),
            One("Bhutan", "Thimphu", "Paro"),
            One("Bangladesh", "Dhaka", "Chittagong"),
            One("Sri Lanka", "Colombo", "Kandy", "Galle"),
            One("Maldives", "Malé"),

            // ---- East & Southeast Asia ----
            One("China", "Beijing", "Shanghai", "Xi'an", "Guangzhou"),
            One("Mongolia", "Ulaanbaatar"),
            One("Japan", "Tokyo", "Kyoto", "Osaka", "Hiroshima"),
            One("South Korea", "Seoul", "Busan", "Incheon"),
            One("North Korea", "Pyongyang"),
            One("Taiwan", "Taipei", "Kaohsiung"),
            One("Vietnam", "Hanoi", "Ho Chi Minh City", "Da Nang"),
            One("Laos", "Vientiane", "Luang Prabang"),
            One("Cambodia", "Phnom Penh", "Siem Reap"),
            One("Thailand", "Bangkok", "Chiang Mai", "Phuket"),
            One("Myanmar", "Naypyidaw", "Yangon", "Bagan"),
            One("Malaysia", "Kuala Lumpur", "George Town", "Malacca"),
            One("Singapore", "Singapore"),
            One("Indonesia", "Jakarta", "Bali", "Yogyakarta"),
            One("Philippines", "Manila", "Cebu", "Davao"),
            One("Brunei", "Bandar Seri Begawan"),
            One("Timor-Leste", "Dili"),

            // ---- Africa ----
            One("Egypt", "Cairo", "Alexandria", "Luxor", "Aswan"),
            One("Libya", "Tripoli", "Benghazi"),
            One("Tunisia", "Tunis", "Sousse", "Kairouan"),
            One("Algeria", "Algiers", "Oran", "Constantine"),
            One("Morocco", "Rabat", "Marrakesh", "Casablanca", "Fes"),
            One("Sudan", "Khartoum", "Omdurman"),
            One("South Sudan", "Juba"),
            One("Ethiopia", "Addis Ababa", "Gondar", "Lalibela"),
            One("Eritrea", "Asmara"),
            One("Djibouti", "Djibouti"),
            One("Somalia", "Mogadishu"),
            One("Kenya", "Nairobi", "Mombasa"),
            One("Uganda", "Kampala"),
            One("Tanzania", "Dodoma", "Dar es Salaam", "Zanzibar City"),
            One("Rwanda", "Kigali"),
            One("Burundi", "Gitega", "Bujumbura"),
            One("Democratic Republic of the Congo", "Kinshasa", "Lubumbashi"),
            One("Republic of the Congo", "Brazzaville"),
            One("Central African Republic", "Bangui"),
            One("Cameroon", "Yaoundé", "Douala"),
            One("Nigeria", "Abuja", "Lagos", "Kano"),
            One("Niger", "Niamey"),
            One("Chad", "N'Djamena"),
            One("Mali", "Bamako", "Timbuktu"),
            One("Burkina Faso", "Ouagadougou"),
            One("Senegal", "Dakar", "Saint-Louis"),
            One("Gambia", "Banjul"),
            One("Guinea", "Conakry"),
            One("Guinea-Bissau", "Bissau"),
            One("Sierra Leone", "Freetown"),
            One("Liberia", "Monrovia"),
            One("Ivory Coast", "Yamoussoukro", "Abidjan"),
            One("Ghana", "Accra", "Kumasi"),
            One("Togo", "Lomé"),
            One("Benin", "Porto-Novo", "Cotonou"),
            One("Mauritania", "Nouakchott"),
            One("Cape Verde", "Praia"),
            One("Sao Tome and Principe", "São Tomé"),
            One("Equatorial Guinea", "Malabo"),
            One("Gabon", "Libreville"),
            One("Angola", "Luanda"),
            One("Zambia", "Lusaka", "Livingstone"),
            One("Malawi", "Lilongwe", "Blantyre"),
            One("Mozambique", "Maputo"),
            One("Zimbabwe", "Harare", "Bulawayo", "Victoria Falls"),
            One("Botswana", "Gaborone"),
            One("Namibia", "Windhoek", "Swakopmund"),
            One("South Africa", "Pretoria", "Cape Town", "Johannesburg", "Durban"),
            One("Lesotho", "Maseru"),
            One("Eswatini", "Mbabane"),
            One("Madagascar", "Antananarivo"),
            One("Mauritius", "Port Louis"),
            One("Seychelles", "Victoria"),
            One("Comoros", "Moroni"),

            // ---- North & Central America, Caribbean ----
            One("United States", "Washington, D.C.", "New York", "Los Angeles", "Chicago", "San Francisco"),
            One("Canada", "Ottawa", "Toronto", "Vancouver", "Montreal"),
            One("Mexico", "Mexico City", "Guadalajara", "Cancún", "Oaxaca"),
            One("Guatemala", "Guatemala City", "Antigua"),
            One("Belize", "Belmopan", "Belize City"),
            One("Honduras", "Tegucigalpa"),
            One("El Salvador", "San Salvador"),
            One("Nicaragua", "Managua", "Granada"),
            One("Costa Rica", "San José"),
            One("Panama", "Panama City"),
            One("Cuba", "Havana", "Trinidad"),
            One("Jamaica", "Kingston", "Montego Bay"),
            One("Haiti", "Port-au-Prince"),
            One("Dominican Republic", "Santo Domingo", "Punta Cana"),
            One("Bahamas", "Nassau"),
            One("Barbados", "Bridgetown"),
            One("Trinidad and Tobago", "Port of Spain"),
            One("Saint Lucia", "Castries"),
            One("Grenada", "St. George's"),
            One("Saint Vincent and the Grenadines", "Kingstown"),
            One("Antigua and Barbuda", "St. John's"),
            One("Dominica", "Roseau"),
            One("Saint Kitts and Nevis", "Basseterre"),

            // ---- South America ----
            One("Brazil", "Brasília", "Rio de Janeiro", "São Paulo", "Salvador"),
            One("Argentina", "Buenos Aires", "Córdoba", "Mendoza"),
            One("Chile", "Santiago", "Valparaíso"),
            One("Uruguay", "Montevideo", "Punta del Este"),
            One("Paraguay", "Asunción"),
            One("Bolivia", "Sucre", "La Paz"),
            One("Peru", "Lima", "Cusco", "Arequipa"),
            One("Ecuador", "Quito", "Guayaquil"),
            One("Colombia", "Bogotá", "Medellín", "Cartagena"),
            One("Venezuela", "Caracas", "Maracaibo"),
            One("Guyana", "Georgetown"),
            One("Suriname", "Paramaribo"),

            // ---- Oceania ----
            One("Australia", "Canberra", "Sydney", "Melbourne", "Brisbane"),
            One("New Zealand", "Wellington", "Auckland", "Queenstown"),
            One("Fiji", "Suva"),
            One("Papua New Guinea", "Port Moresby"),
            One("Solomon Islands", "Honiara"),
            One("Vanuatu", "Port Vila"),
            One("Samoa", "Apia"),
            One("Tonga", "Nukuʻalofa"),
            One("Kiribati", "South Tarawa"),
            One("Micronesia", "Palikir"),
            One("Marshall Islands", "Majuro"),
            One("Palau", "Ngerulmud"),
            One("Nauru", "Yaren"),
            One("Tuvalu", "Funafuti"),
        };
    }
}
